services:
  - type: web
    name: shopnellore
    env: node
    rootDir: .
    buildCommand: |
      npm install
      cd frontend
      npm install
      npm run build
      cd ..
      mkdir -p frontend/build
      mv frontend/build ./frontend/
    startCommand: npm start
    nodeVersion: 16.x
    envVars:
      - key: NODE_ENV
        value: production 